import express from "express";
import authRoutes from "./auth.routes.js";
import categoryRoutes from "./category.routes.js";
import productRoutes from "./product.routes.js";
import cartRoutes from "./cart.routes.js";
import wishlistRoutes from "./wishlist.routes.js";
import reviewRoutes from "./review.routes.js";
import orderRoutes from "./order.routes.js";
import paymentRoutes from "./payment.routes.js";
import adminRoutes from "./admin.routes.js";
import userRoutes from "./user.routes.js";

const router = express.Router();
router.use("/auth",      authRoutes);
router.use("/categories", categoryRoutes);
router.use("/products",  productRoutes);
router.use("/cart",      cartRoutes);
router.use("/wishlist",  wishlistRoutes);
router.use("/products/:productId/reviews", reviewRoutes);
router.use("/orders",    orderRoutes);
router.use("/payments",  paymentRoutes);
router.use("/admin",     adminRoutes);
router.use("/users",     userRoutes);
export default router;
